var x, y, z;
x = 3;
y = -2;
z = 3;
console.log(x, y, z);
x = 4;
console.log(x);
z = x + y;
console.log(z);
y = "Мама";
console.log(x, y, z);
var a = 8, b = 3, c;
console.log(c);
var sum, diff, mul, div, mod;
sum = a + b;
diff = a - b;
mul = a * b;
div = a / b;
mod = a % b;
console.log(sum, diff, mul, div, mod);
console.log( (2 + 2) * 2);
console.log("Сумма a и b равна", sum);
console.log("Сумма", a, "и", b, "равна", sum);