export const ADD_PRODUCT = "PRODUСT_ADD";
export const DELETE_PRODUCT = "PRODUСT_DELETE";
export const EDIT_PRODUCT = "PRODUСT_EDIT";
export const FAVORITE_PRODUCT = "PRODUCT_FAVORITE";
export const UNFAVORITE_PRODUCT = "PRODUCT_UNFAVORITE";